### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Zekiah-A** [open-mc/desktop#1]
- [ ] World and chunk rendering.
- [ ] Finish adding all Item definitions, everything past https://github.com/open-mc/client/blob/687e4606649c0fb329e3c0b78791ca19fa82cabd/cli/defs.js#L209 needs to be added into Game/Definitions/
- [ ] Port the buttons at the bottom of the serverlist page to use grid.
- [ ] Design some UI for the account and profile page, for now, just a control that allows you to view a skin, then a button to upload a skin to the game (could use a native file dialog), and perhaps some other things if you can think of that.
- [ ] Use the view object passed into the render func on controls to somehow clip the content on controls like the textinput and serverlist control. Implement some kind of scrolling/virtualisation for both of these controls as well (can be done with view and the move method).
